sudo: false
language: java
jdk:
- oraclejdk8
script:
- ./run.sh
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  email:
    - pruthula@gmail.com
    - rangasaiy33@gmail.com
  on_success: always
